### ISSUE TITLE
[Update] Nextcloud to 28.0.7 (or 29.0.3)

### ISSUE THREAD

**Issue by loralb** [getumbrel/umbrel-apps#1238]
Hello, thank you so much for all your work!
I noticed that the Nextcloud app is lagging behind (currently version 28.0.3 is available on umbrel, IIRC), so this is why I opened this request; the list of change is long, so I'll leave here a few links:
- [28.0.4](https://github.com/nextcloud/server/releases/tag/v28.0.4)
- [28.0.5](https://github.com/nextcloud/server/releases/tag/v28.0.5rc1)
- [28.0.6](https://github.com/nextcloud/server/releases/tag/v28.0.6rc1)
- [28.0.7](https://github.com/nextcloud/server/releases/tag/v28.0.7)

**Comment by dennysubke** [comment]
❗❗❗

I have already mentioned it several times in the community and with support. Nothing has happened for weeks, although the current version has significant security risks. I hope that an update to version 29.03 will now be released.

https://community.umbrel.com/t/please-update-nextcloud-significant-security-risks/17937

**Comment by loralb** [comment]
Nextcloud updated to 29.0.4! Thank you!

**Comment by nmfretz** [comment]
You're welcome @loralb. We'll be keeping Nextcloud updated in a timely fashion from here on out. Nextcloud updates can be quite finicky so please let me know if you run into any issues when updating.

**Comment by dennysubke** [comment]
Thanks for the update and the good work.

After the update I get the following error messages:

- Your data directory and files are probably accessible from the Internet. The .htaccess file is not working. It is strongly recommended that you configure your web server so that the data directory is no longer accessible from the Internet or that you move it out of the document root directory of the web server.

- Your "trusted_proxies" setting is not set correctly, it should be an array of IP addresses - optionally with a range in CIDR notation. You can find more information in the documentation.

I use Cloudflare and have already entered all IP address ranges in the Config.php under Trusted Proxies. Any ideas?
