### ISSUE TITLE
Pi-Hole does not implement the app_proxy app

### ISSUE THREAD

**Issue by DavidGarciaCat** [getumbrel/umbrel-apps#1463]
As part of my submission for the [Zabbix App](https://github.com/getumbrel/umbrel-apps/pull/1376), we have had a discussion where I was encouraged to [use the `app_proxy`](https://github.com/getumbrel/umbrel-apps/pull/1376#discussion_r1758065260) instead of exposing the App itself.

Given I have used pi-hole as my example, I need to say this requirement doesn't exist, so it should be implemented for consistency:

https://github.com/getumbrel/umbrel-apps/blob/0248ecd0231ba50f8df8490d3041e5147c278b72/pi-hole/docker-compose.yml#L1-L5

**Comment by nmfretz** [comment]
Hi @DavidGarciaCat, good eye. This is actually on purpose in the case of Pi-hole. What's happening here is that Pi-hole is running in host networking mode, meaning that the app uses the host machine’s network interfaces directly, without any network isolation. 

https://github.com/getumbrel/umbrel-apps/blob/97713cba7bba5953b9b539e05c174ae00360ba12/pi-hole/docker-compose.yml#L10

Unfortunately for us, using something like the app_proxy container is not possible when the app is running in host network mode. There are a few apps that run in Docker's host networking mode (e.g., Home Assistant, Adguard Home, Plex, etc).
In all cases, we have opted to run them in host network mode instead of bridge mode so as to not restrict the app's functionality to the point where it is no longer useful to run. We have some ideas for how to do this better in the future.

With Pi-hole for instance, host networking allows it to function as a DHCP server.

**Comment by DavidGarciaCat** [comment]
I understand what you say.

If you don't mind me asking, why use the Host's network mode instead of mapping all the required ports? It would end up doing the same while keeping consistency across all apps, don't you think?

**Comment by nmfretz** [comment]
> If you don't mind me asking, why use the Host's network mode instead of mapping all the required ports? It would end up doing the same while keeping consistency across all apps

Unfortunately, mapping all necessary ports in bridge network mode does not solve our issue. It allows communication via explicitly mapped ports, but it doesn't allow full network access, which is required for protocols like multicast, broadcast, etc

A couple examples from the app store right now:

Pi-Hole: In bridge mode, Pi-hole can’t receive DHCP requests from devices due to broadcast traffic restrictions, breaking its DHCP server functionality.

Home Assistant:  Bridge mode blocks multicast traffic needed for discovering devices on your local network

Plex: Discovery features such as DLNA won't work correctly in bridge mode because these rely on multicast or broadcast packets, which do not traverse the NAT boundary created by the bridge network.

**Comment by DavidGarciaCat** [comment]
Thanks for the detailed reply
