### ISSUE TITLE
Undocumented variables / interfacing with other Umbrel apps

### ISSUE THREAD

**Issue by PlebeiusGaragicus** [getumbrel/umbrel-apps#276]
https://github.com/getumbrel/umbrel-apps/blob/e2796a083c23a82a4002466392c48ab8e9b275b3/btcpay-server/docker-compose.yml#L18-L30

I'm looking through the code of some Umbrel apps and finding variables like APP_BITCOIN_NODE_IP, etc that I can't find documentation for.  I'd love to find a way to talk to other apps on my Umbrel node, but I'm not able to find useful documentation for how to do that.

**Comment by nevets963** [comment]
Whenever you see an environment variable such as `$APP_BITCOIN_XYZ`, these are being 'exported' from the app (here Bitcoin), so that another app can use that state.

For example, here is everything that the Bitcoin app exports: https://github.com/getumbrel/umbrel-apps/blob/feaf56a3a435289dde42471019326d2630f49aad/bitcoin/exports.sh

Within that shell script, there is some logic to determine the correct port for RPC, and then the environment variable `$APP_BITCOIN_RPC_PORT` is set correctly and 'exported' which another app can then use to communicate with `bitcoind`.

**Comment by nevets963** [comment]
@PlebeiusGaragicus Does the above satisfy your question? There is also some detail documented here: https://github.com/getumbrel/umbrel-apps#2-%EF%B8%8Fpackaging-the-app-for-umbrel
