### ISSUE TITLE
LibreOffice not working 

### ISSUE THREAD

**Issue by johnpc** [getumbrel/umbrel-apps#319]
I was excited to see LibreOffice added to the App Store in https://github.com/getumbrel/umbrel-apps/pull/216

However, when I installed it myself, I found that it does not load properly.

At first I saw a CORS issue that I thought could be a cause, but this issue did not persist across refreshes. 

```
Access to internal resource at 'http://umbrel.local:2000/?origin=host&app=libreoffice&path=%2Fmanifest.json' (redirected from 'http://umbrel.local:5001/manifest.json') from origin 'http://umbrel.local:5001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I've tried it across browsers and I get the same result

<img width="1680" alt="Screen Shot 2022-12-02 at 12 46 34 PM" src="https://user-images.githubusercontent.com/4824042/205353881-aec5275c-2a4e-42e8-9140-cab37c21c286.png">

Screen recording available here: https://jpc.io/r/umbrel-libreoffice.mov

**Comment by nevets963** [comment]
@johnpc Could you confirm a couple of things for me?

- What version of Umbrel are you running?
- Could your browser or any installed plugins are affecting sessions, cookies, etc?

Although I note that error in your console, could that have been from before you logged in to access LibreOffice? Because I see (from your video) that the 'environment' for LibreOffice has loaded fine. In the bottom left corner, I can see the icons for the different applications that are part of LibreOffice - that you can click to load.

**Comment by IMPranshu** [comment]
Running perfectly @johnpc 


<img width="1503" alt="Screenshot 2023-07-11 at 12 33 43 PM" src="https://github.com/getumbrel/umbrel-apps/assets/43396684/e44ff64f-51de-4cc0-afe8-d2cfc1f9adcc">

Can you describe what is the issue that you are facing? Did you restart Umbrel once? There might be some internal issues at that particular moment.
