### ISSUE TITLE
Samourai Server - Pairing QR Error

### ISSUE THREAD

**Issue by pardus79** [getumbrel/umbrel-apps#343]
The Samourai Server app provides a QR for pairing over clearnet, with a clearnet (local umbrel) address but will not provide a tor address. Tried launching app from tor browser and the QR won't display, nor can I access the dojo maintenance tool in tor.

The dojo maintenance tool over clearnet also doesn't provide a tor address.

**Comment by JohnnyVicious** [comment]
Can confirm, the address in the QR is http://notyetset.onion

**Comment by anon7435** [comment]
I've had the same issue since i installed the Samurai Server app. After some days trying to fix it, the error seems because there isn't any configuration written in umbrel/app-data/samourai-server/torrc.template refered to samourai-server dojo hidden service, only with whirlpool. I don't have much experience in creating hidden service in tor, but there u have my torrc.template that i use.

`# samourai-server whirlpool Hidden Service
HiddenServiceDir /data/app-$APP_ID-whirlpool
HiddenServicePort 80 samourai-server_whirlpool_1:8898

# samourai-server dojo Hidden Service
HiddenServiceDir /data/app-$APP_ID-dojo
HiddenServicePort 3009 samourai-server_nginx_1:3009`

3009 is the port used in samourai-server_nginx_1 container. Be careful with that, because in my docker-compose deploy i found that i cant still connect to dojo after adding the torrc conf, so i needed to change the nginx listen port from 80 to 3009. This conf is in umbrel/app-data/samourai-server/nginx/mainnet.conf

Restart umbrel, and you should see that it has been created an .onion route in umbrel/tor/data/app-samourai-server-dojo/hostname. This step is done by umbrel/app-data/samourai-server/hooks/pre-start (if you need to check it).

Scan the QR and add the port :3009. For me it works, i hope for you too.

**Comment by nevets963** [comment]
Hey folks, this issue has been resolved in this PR: https://github.com/getumbrel/umbrel-apps/pull/401 Just an update through the Umbrel App Store is required and you'll be able to get remote access again.
