### ISSUE TITLE
unable to install node-red which has dependency of btc-node

### ISSUE THREAD

**Issue by gasolin** [getumbrel/umbrel-apps#36]
unable to install node-red due to missing packages dependency (when not plan to install btc-node)

<img width="409" alt="截圖 2022-06-14 下午10 36 14" src="https://user-images.githubusercontent.com/748808/173604421-de9f8195-cd3e-4217-b29e-c1c74443f421.png">
d

**Comment by Xosten** [comment]
This is weird.... @lukechilds Any ideas why Node-Red required those dependencies?

**Comment by lukechilds** [comment]
Yeah sorry about that, that's because the initial version of Node-Red was created with Bitcoin/electrs/Lightning integration, so it does depend on them. We don't have support (yet) for optional dependencies which is that these Bitcoin deps would ideally be here.

**Comment by Xosten** [comment]
> Yeah sorry about that, that's because the initial version of Node-Red was created with Bitcoin/electrs/Lightning integration, so it does depend on them. We don't have support (yet) for optional dependencies which is that these Bitcoin deps would ideally be here.

Word, but if they are optional, why not just remove them and mention it in the description ?

**Comment by lukechilds** [comment]
Because we haven't built the optional functionality into Umbrel yet. All apps are sandboxed by default and cannot communicate with each other unless explicitly allowed. So the way Umbrel works today either Node-RED explicitly depends on the other apps and can communicate with them, or does not depend on them and is not allowed to communicate with them.

Optional dependencies is something we plan to support but is not implemented yet. I guess for now a quick workaround for Node-RED would be to ship two versions of the app, one that depends on Bitcoin and one that doesn't, that way we can satisfy both sets of users today (users who want to install Node-RED without installing Bitcoin, and users who want to integrate Node-RED with Bitcoin apps).

And then we can deprecate the "Node-RED (Bitcoin)" app variant in the future when we support optional dependencies.

**Comment by Xosten** [comment]
Got it, makes sense indeed. Downside of it if there's other apps that have optional dependencies would be to have duplicated entries 🤷🏻 ...

**Comment by lukechilds** [comment]
Yeah, definitely not ideal, just a short term workaround.

**Comment by Xosten** [comment]
Should I try to come up with an PR ?
