### ISSUE TITLE
Owncloud not accessible with tailscale

### ISSUE THREAD

**Issue by 0xtlt** [getumbrel/umbrel-apps#598]
Hello,

You allow to use tailscale to easily connect to its node, however I currently have a problem with owncloud where I get the following error when connecting from the tailscale ip:
```Access through untrusted domain
Please contact your administrator. If you are an administrator, edit the "trusted_domains" setting in config/config.php like the example in config.sample.php.
```

Is it possible to have an automatic configuration for this or a trick to unblock the situation?

**Comment by nmfretz** [comment]
Hey @0xtlt and others who make their way here. If this is for `Nextcloud` then here are some tips on accessing your instance via Tailscale.

1) If you are using the default tailscale short-domain to access your umbrel (which will be `http://umbrel` by default), this will work out-of-the-box without needing to do any extra configuration. You can just navigate to the Nextcloud UI by clicking on the app icon from the homescreen of umbrelOS.

2) If you are accessing your umbrel using a Tailscale IP address (or any other private/public IP address that you have configured for that matter) then you will need to add this IP to your Nextcloud's `config.php` file. Otherwise, you will be met with this screen:
<img width="773" alt="image" src="https://github.com/getumbrel/umbrel-apps/assets/85373263/3f8d6b09-05a3-4b2d-bafc-4ee8338a64c9">

The config.php file is located at `/home/umbrel/umbrel/app-data/nextcloud/data/nextcloud/config/config.php`

The file will include a block that looks something like this:

```
'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'umbrel.local:8081',
    2 => 'not-enabled.onion',
    3 => 'umbrel:8081',
    ... and on and on
  ),
  ```
  
 You need to add your tailscale IP to this array.

From the homescreen on umbrelOS 1.1 and greater you can:
- navigate to Settings > Advanced Settings > Terminal > umbrelOS. 
- run the following command to open the config.php file in a text editor:
`sudo nano /home/umbrel/umbrel/app-data/nextcloud/data/nextcloud/config/config.php`
- add another line to the array with `<your-needed-ip>:8081`. This might look something like:
`12 => '100.121.58.71:8081',`
- make sure all indentation is correct
- save the file by pressing "Ctrl+X", then "y", then "Enter"
- There is no need to restart Nexcloud, you will now be able to access it by the IP you added.
