### ISSUE TITLE
Lightning Shell 0.1.10-build-1 deprecated

### ISSUE THREAD

**Issue by tlindi** [getumbrel/umbrel-apps#601]
Lightning Shell Latest update is about year old AFAIK 
https://github.com/getumbrel/umbrel/pull/1291

Umbrel App Store says:
![image](https://user-images.githubusercontent.com/7249767/211558710-4e680b40-0f26-4b63-9928-ad3c81470aa1.png)

I'm looking for way to install this onto Umbrel via WebUI
https://github.com/accumulator/charge-lnd/releases/tag/v0.2.13

Does it get installed and is Shell working in general with Umbrel 0.5.3?

**Comment by nmfretz** [comment]
Ah ya, Lightning Shell was deprecated by request of the app developer since it is no longer maintained: https://github.com/getumbrel/umbrel-apps/pull/98

> I'm looking for way to install this onto Umbrel via WebUI

There are currently two ways to run anything on umbrelOS outside of the official app store:
- Download Portainer (https://apps.umbrel.com/app/portainer) from the Umbrel app store
- Community App Stores: https://github.com/getumbrel/umbrel-community-app-store
